+incdir+../enc
+incdir+../ip/axi_2t1_int/src

../ip/sync_fifo.v
../ip/sync_fifo_af.v
../ip/async_fifo_fwft_256w.v
../ip/ubwc_axi_wr_256to64.v
../ip/ubwc_sync_fifo_fwft.sv
../ip/ubwc_sram_1rw.v
../enc/ubwc_enc_rst_mdl.v
../enc/ubwc_enc_apb_reg_blk.v
../enc/ubwc_enc_otf_data_packer.v
../enc/ubwc_enc_line_to_tile.v
../enc/ubwc_enc_otf_to_tile_top.v
../enc/ubwc_enc_tileaddr.sv
../enc/ubwc_enc_vivo_top.sv
../enc/ubwc_enc_meta_addr_gen.sv
../enc/ubwc_tile_enc_axi_wcmd_gen.v
../enc/ubwc_enc_meta_axi_wcmd_gen_v2.v
../enc/ubwc_enc_wrapper_top.sv
../../vrf/src/otf_master_driver.sv
../enc/axi_2t1_int_DW_axi.v
