+incdir+../dec
+incdir+../enc
+incdir+../ip/axi_2t1_int/src

../ip/mg_sync_fifo.v
../dec/ubwc_meta_simple_fifo.v
../dec/ubwc_dec_meta_get_cmd_gen.v
../dec/ubwc_dec_meta_axi_rcmd_gen.v
../dec/ubwc_dec_meta_axi_rdata_to_sram.v
../dec/ubwc_dec_axi_rd_interconnect.v
../dec/ubwc_dec_meta_data_from_sram.v
../ip/ubwc_axi_rd_256to64.v
../ip/ubwc_std_single_port_sram.v
../dec/ubwc_dec_meta_pingpong_sram.v
../dec/ubwc_dec_rstn_gen.v
../dec/ubwc_dec_apb_reg_blk.v
../dec/ubwc_dec_meta_data_gen.v
../dec/ubwc_dec_meta_data_decode.v
../dec/ubwc_tileaddr.v
../dec/ubwc_dec_tile_arcmd_gen.v
../dec/ubwc_dec_vivo_top.v
../dec/ubwc_dec_tile_to_otf.v
../dec/ubwc_dec_tile_to_line_writer.v
../dec/ubwc_dec_tile_to_line_sram_fetcher.v
../dec/ubwc_dec_otf_driver.v
../ip/async_fifo_fwft_256w.v
../ip/sync_fifo_fwft_262w_512d.v
../ip/sram_pdp_8192x128.v
../dec/ubwc_dec_wrapper_top.v

../ip/ubwc_axi_wr_64to256.v
../ip/ubwc_axi_wr_256to64.v
../ip/ubwc_sram_1rw.v
../enc/ubwc_enc_rst_mdl.v
../enc/ubwc_enc_apb_reg_blk.v
../enc/ubwc_enc_otf_data_packer.v
../enc/ubwc_enc_line_to_tile.v
../enc/ubwc_enc_otf_to_tile_top.v
../enc/ubwc_enc_tileaddr.sv
../enc/ubwc_enc_vivo_top.sv
../enc/ubwc_enc_meta_addr_gen.sv
../enc/ubwc_tile_enc_axi_wcmd_gen.v
../enc/ubwc_enc_meta_axi_wcmd_gen.v
../enc/axi_2t1_int_DW_axi.v
../enc/ubwc_enc_wrapper_top.sv
../ubwc_wrapper_top.v
../../vrf/src/otf_master_driver.sv
