+incdir+../ip/ubwc_x2x/src

../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_cc_constants.vh
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_constants.vh
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm_params.vh
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_all_includes.vh
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm05.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm06.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm07.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm99.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm21.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm51.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm57.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm58.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm65.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_bcm66.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_fifo_s1_sf.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_busmux.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_busmux_ohsel.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sd_fifo.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_w_ch_fifos.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sp_r_rsfifos.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sp_b_rsfifos.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_et.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_mp_a.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_mp_rb.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_mp_wfc.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_mp_w.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_mp.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_addr_alen.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_xact_ctrl.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_rs.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sp_wfc.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sp_a.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_r_dopack.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_r_packer.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_r_pusher.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_ue.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sp_r.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sp_b.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sp_w.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sp_w_top.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x_sp.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x.v
../ip/ubwc_x2x/src/ubwc_x2x_DW_axi_x2x-undef.v
