#!/usr/bin/env python3
"""Run wrapper regressions over R7130 vector directories.

The existing fake-all regression is TajMahal oriented.  This helper prepares
per-vector build directories, parameterizes the generic ENC/DEC wrapper TBs,
and preserves each run directory so FSDB waves remain available.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import os
import re
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SIM_DIR = PROJECT_ROOT / "vrf" / "sim"
VECTOR_ROOT = PROJECT_ROOT / "vrf" / "vector"
OTF_CASE_TOOL = PROJECT_ROOT / "vrf" / "scripts" / "otf_case_tool.py"
ENV_SCRIPT = PROJECT_ROOT / "prj_setup.env"

ENC_TOP = "tb_ubwc_enc_wrapper_top_tajmahal_cases"
DEC_TOP = "tb_ubwc_dec_wrapper_top_tajmahal_cases"


def ceil_div(value: int, divisor: int) -> int:
    return (value + divisor - 1) // divisor


def align_up(value: int, alignment: int) -> int:
    return ((value + alignment - 1) // alignment) * alignment


def count_words64(path: Path) -> int:
    with path.open() as fh:
        return sum(1 for line in fh if line.strip() and not line.startswith("@"))


def strip_at_lines(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    with src.open() as fin, dst.open("w") as fout:
        for line in fin:
            if line.startswith("@"):
                continue
            fout.write(line)


def load_words64(path: Path) -> list[int]:
    words: list[int] = []
    with path.open() as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("@"):
                continue
            words.append(int(line, 16))
    return words


def write_words64(path: Path, words: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as fh:
        for word in words:
            fh.write(f"{word & ((1 << 64) - 1):016x}\n")


def word_byte(words: list[int], byte_idx: int) -> int:
    if byte_idx < 0:
        return 0
    word_idx = byte_idx // 8
    byte_off = byte_idx % 8
    if word_idx >= len(words):
        return 0
    return (words[word_idx] >> (byte_off * 8)) & 0xff


def active_linear_words(case: VectorCase, plane: int) -> list[int]:
    src_words = load_words64(case.linear_y if plane == 0 else case.linear_uv)
    if plane == 0:
        active_h = case.height
        row_bytes = case.width * case.bytes_per_pixel
    else:
        active_h = case.active_uv_height
        row_bytes = case.width if case.fmt == "nv12" else case.width * case.bytes_per_pixel
    total_bytes = active_h * row_bytes
    out_words: list[int] = []
    for word_idx in range(ceil_div(total_bytes, 8)):
        word = 0
        for byte_idx in range(8):
            src_idx = word_idx * 8 + byte_idx
            if src_idx < total_bytes:
                word |= word_byte(src_words, src_idx) << (byte_idx * 8)
        out_words.append(word)
    return out_words


def meta_byte_offset(tile_x: int, tile_y: int, meta_pitch: int) -> int:
    return ((tile_y >> 4) * meta_pitch * 16) + \
        ((tile_x >> 4) << 8) + \
        (((tile_y >> 3) & 1) << 7) + \
        (((tile_x >> 3) & 1) << 6) + \
        ((tile_y & 7) << 3) + \
        (tile_x & 7)


def enc_generated_meta_byte(raw_byte: int) -> int:
    return 0x10 | (((raw_byte >> 1) & 0x7) << 1)


def normalize_enc_meta_words(case: VectorCase,
                             plane: int,
                             src_words: list[int]) -> list[int]:
    """Build ENC expected metadata for the active-tile stream.

    Source UBWC vectors keep aligned-width padding metadata.  The ENC wrapper
    fake regression feeds real active pixels only, so it should compare only
    metadata generated by active tile coordinates.  Words are packed in the RTL
    stream order: x within each 8-tile metadata word occupies LSB to MSB.
    """

    if plane == 0:
        active_cols = case.tile_cols
        active_rows = case.active_y_tile_rows
        meta_pitch = case.meta_pitch_y
        word_count = case.meta_y_words64
    else:
        active_cols = case.tile_cols
        active_rows = case.active_uv_tile_rows
        meta_pitch = case.meta_pitch_uv
        word_count = case.meta_uv_words64

    out_words = [0] * word_count
    if meta_pitch == 0:
        return out_words

    for tile_y in range(active_rows):
        for tile_x_base in range(0, active_cols, 8):
            byte_offset = meta_byte_offset(tile_x_base, tile_y, meta_pitch)
            word_idx = byte_offset // 8
            if word_idx >= word_count or word_idx >= len(src_words):
                continue

            valid_bytes = min(8, active_cols - tile_x_base)
            src_word = src_words[word_idx]
            msb_order = [(src_word >> (8 * (7 - idx))) & 0xff for idx in range(8)]
            lsb_order = [(src_word >> (8 * idx)) & 0xff for idx in range(8)]
            msb_score = sum(1 for value in msb_order[:valid_bytes] if value != 0)
            lsb_score = sum(1 for value in lsb_order[:valid_bytes] if value != 0)
            src_bytes = lsb_order if lsb_score > msb_score else msb_order

            word = 0
            for idx in range(valid_bytes):
                word |= enc_generated_meta_byte(src_bytes[idx]) << (8 * idx)
            out_words[word_idx] = word

    return out_words


def p010_source_byte(words: list[int], byte_idx: int) -> int:
    sample_byte_idx = (byte_idx // 2) * 2
    sample = word_byte(words, sample_byte_idx) | (word_byte(words, sample_byte_idx + 1) << 8)
    sample &= 0xFFC0
    return (sample >> 8) & 0xff if (byte_idx & 1) else sample & 0xff


def macro_tile_slot(tile_x_mod8: int, tile_y_mod8: int) -> int:
    table = [
        [0, 6, 3, 5, 4, 2, 7, 1],
        [7, 1, 4, 2, 3, 5, 0, 6],
        [10, 12, 9, 15, 14, 8, 13, 11],
        [13, 11, 14, 8, 9, 15, 10, 12],
        [4, 2, 7, 1, 0, 6, 3, 5],
        [3, 5, 0, 6, 7, 1, 4, 2],
        [14, 8, 13, 11, 10, 12, 9, 15],
        [9, 15, 10, 12, 13, 11, 14, 8],
    ]
    return table[tile_x_mod8][tile_y_mod8]


def rgba_tile_base_word(tile_x: int, tile_y: int, pitch_bytes: int, highest_bank: int = 16) -> int:
    macro_tile_x = tile_x // 4
    macro_tile_y = tile_y // 4
    addr_bytes = (
        pitch_bytes * (macro_tile_y * 4) * 4
        + macro_tile_x * 4096
        + macro_tile_slot(tile_x % 8, tile_y % 8) * 256
    )
    if (16 * pitch_bytes) % (1 << highest_bank) == 0:
        tile_row_pixels = tile_y * 4
        bit_val = ((addr_bytes >> (highest_bank - 1)) & 1) ^ ((tile_row_pixels >> 4) & 1)
        if bit_val:
            addr_bytes |= 1 << (highest_bank - 1)
        else:
            addr_bytes &= ~(1 << (highest_bank - 1))
    if (16 * pitch_bytes) % (1 << (highest_bank + 1)) == 0:
        tile_row_pixels = tile_y * 4
        bit_val = ((addr_bytes >> highest_bank) & 1) ^ ((tile_row_pixels >> 5) & 1)
        if bit_val:
            addr_bytes |= 1 << highest_bank
        else:
            addr_bytes &= ~(1 << highest_bank)
    return addr_bytes >> 3


def plane_tile_base_word(
    tile_x: int,
    tile_y: int,
    tile_width: int,
    tile_height: int,
    pitch_bytes: int,
    highest_bank: int,
    bpp: int,
) -> int:
    macro_tile_x = tile_x // 4
    macro_tile_y = tile_y // 4
    addr_bytes = (
        pitch_bytes * (macro_tile_y * 4) * tile_height
        + macro_tile_x * 4096
        + macro_tile_slot(tile_x % 8, tile_y % 8) * 256
    )
    if (16 * pitch_bytes) % (1 << highest_bank) == 0:
        if ((bpp == 1) and (tile_width == 32) and (tile_height == 8)) or (
            (bpp == 2) and (tile_width == 16) and (tile_height == 8)
        ):
            tile_row_pixels = (tile_y * tile_height) >> 5
        else:
            tile_row_pixels = (tile_y * tile_height) >> 4
        bit_val = ((addr_bytes >> (highest_bank - 1)) & 1) ^ (tile_row_pixels & 1)
        if bit_val:
            addr_bytes |= 1 << (highest_bank - 1)
        else:
            addr_bytes &= ~(1 << (highest_bank - 1))
    if (16 * pitch_bytes) % (1 << (highest_bank + 1)) == 0:
        if ((bpp == 1) and (tile_width == 32) and (tile_height == 8)) or (
            (bpp == 2) and (tile_width == 16) and (tile_height == 8)
        ):
            tile_row_pixels = (tile_y * tile_height) >> 6
        else:
            tile_row_pixels = (tile_y * tile_height) >> 5
        bit_val = ((addr_bytes >> highest_bank) & 1) ^ (tile_row_pixels & 1)
        if bit_val:
            addr_bytes |= 1 << highest_bank
        else:
            addr_bytes &= ~(1 << highest_bank)
    return addr_bytes >> 3


def linear_to_dec_tile_words(case: VectorCase, plane: int) -> list[int]:
    src = load_words64(case.linear_y if plane == 0 else case.linear_uv)
    if plane == 0:
        active_h = case.height
        stored_h = max(case.stored_y, active_h)
        out_words = [0] * ((case.pitch_y * stored_h) // 8)
        pitch_bytes = case.pitch_y
    else:
        active_h = case.active_uv_height
        stored_h = max(case.stored_uv, active_h)
        out_words = [0] * ((case.pitch_uv * stored_h) // 8)
        pitch_bytes = case.pitch_uv

    if case.fmt.startswith("rgba"):
        tile_width = 16
        tile_height = 4
        bpp = 4
        tile_base = lambda tx, ty: rgba_tile_base_word(tx, ty, pitch_bytes)
    elif case.fmt == "p010":
        tile_width = 32
        tile_height = 4
        bpp = 2
        tile_base = lambda tx, ty: plane_tile_base_word(tx, ty, 32, 4, pitch_bytes, 16, 2)
    else:
        tile_width = 32
        tile_height = 8
        bpp = 1
        tile_base = lambda tx, ty: plane_tile_base_word(tx, ty, 32, 8, pitch_bytes, 16, 1)

    row_bytes = case.width * bpp if not (case.fmt == "nv12" and plane == 1) else case.width
    tile_row_bytes = tile_width * bpp
    beats_per_tile_row = max(1, tile_row_bytes // 32)
    active_tile_rows = ceil_div(active_h, tile_height)

    for tile_y in range(active_tile_rows):
        for tile_x in range(case.tile_cols):
            dst_base = tile_base(tile_x, tile_y)
            for beat_idx in range(8):
                row_in_tile = beat_idx // beats_per_tile_row
                beat_in_row = beat_idx % beats_per_tile_row
                row_abs = tile_y * tile_height + row_in_tile
                col_byte = tile_x * tile_row_bytes + beat_in_row * 32
                for lane in range(4):
                    word = 0
                    for byte_idx in range(8):
                        src_byte = 0
                        src_col = col_byte + lane * 8 + byte_idx
                        if row_abs < active_h and src_col < row_bytes:
                            src_idx = row_abs * row_bytes + src_col
                            src_byte = p010_source_byte(src, src_idx) if case.fmt == "p010" else word_byte(src, src_idx)
                        word |= src_byte << (byte_idx * 8)
                    dst_idx = dst_base + beat_idx * 4 + lane
                    if 0 <= dst_idx < len(out_words):
                        out_words[dst_idx] = word
    return out_words


def dec_tile_to_linear_words(case: VectorCase, plane: int) -> list[int]:
    src = load_words64(case.tile_uncomp_y if plane == 0 else case.tile_uncomp_uv)
    if plane == 0:
        active_h = case.height
        pitch_bytes = case.pitch_y
    else:
        active_h = case.active_uv_height
        pitch_bytes = case.pitch_uv

    if case.fmt.startswith("rgba"):
        tile_width = 16
        tile_height = 4
        bpp = 4
        tile_base = lambda tx, ty: rgba_tile_base_word(tx, ty, pitch_bytes)
    elif case.fmt == "p010":
        tile_width = 32
        tile_height = 4
        bpp = 2
        tile_base = lambda tx, ty: plane_tile_base_word(tx, ty, 32, 4, pitch_bytes, 16, 2)
    else:
        tile_width = 32
        tile_height = 8
        bpp = 1
        tile_base = lambda tx, ty: plane_tile_base_word(tx, ty, 32, 8, pitch_bytes, 16, 1)

    row_bytes = case.width * bpp if not (case.fmt == "nv12" and plane == 1) else case.width
    tile_row_bytes = tile_width * bpp
    beats_per_tile_row = max(1, tile_row_bytes // 32)
    active_tile_rows = ceil_div(active_h, tile_height)
    out_bytes = bytearray(active_h * row_bytes)

    for tile_y in range(active_tile_rows):
        for tile_x in range(case.tile_cols):
            src_base = tile_base(tile_x, tile_y)
            for beat_idx in range(8):
                row_in_tile = beat_idx // beats_per_tile_row
                beat_in_row = beat_idx % beats_per_tile_row
                row_abs = tile_y * tile_height + row_in_tile
                col_byte = tile_x * tile_row_bytes + beat_in_row * 32
                if row_abs >= active_h:
                    continue
                for lane in range(4):
                    src_word_idx = src_base + beat_idx * 4 + lane
                    src_word = src[src_word_idx] if 0 <= src_word_idx < len(src) else 0
                    for byte_idx in range(8):
                        dst_col = col_byte + lane * 8 + byte_idx
                        if dst_col < row_bytes:
                            out_bytes[row_abs * row_bytes + dst_col] = (src_word >> (byte_idx * 8)) & 0xff

    out_words: list[int] = []
    for word_idx in range(ceil_div(len(out_bytes), 8)):
        word = 0
        for byte_idx in range(8):
            src_idx = word_idx * 8 + byte_idx
            if src_idx < len(out_bytes):
                word |= out_bytes[src_idx] << (byte_idx * 8)
        out_words.append(word)
    return out_words


def parse_int_field(text: str, label: str) -> int:
    match = re.search(rf"^{re.escape(label)}[ \t]*:[ \t]*([0-9]+)", text, re.M)
    if not match:
        raise ValueError(f"Missing field '{label}'")
    return int(match.group(1))


def parse_hex_field(text: str, label: str, default: int = 0) -> int:
    match = re.search(rf"^{re.escape(label)}[ \t]*:[ \t]*(0x[0-9a-fA-F]+)", text, re.M)
    if not match:
        return default
    return int(match.group(1), 16)


def parse_optional_int_field(text: str, label: str, default: int = 0) -> int:
    match = re.search(rf"^{re.escape(label)}[ \t]*:[ \t]*([0-9]+)", text, re.M)
    if not match:
        return default
    return int(match.group(1))


def parse_file_field(text: str, label: str) -> str | None:
    match = re.search(rf"^{re.escape(label)}[ \t]*:[ \t]*(.*)$", text, re.M)
    if not match:
        return None
    value = match.group(1).strip()
    return value or None


@dataclass(frozen=True)
class VectorCase:
    name: str
    path: Path
    fmt: str
    case_id: int
    width: int
    height: int
    stored_y: int
    stored_uv: int
    pitch_y: int
    pitch_uv: int
    meta_pitch_y: int
    meta_pitch_uv: int
    meta_base_y: int
    meta_base_uv: int
    tile_base_y: int
    tile_base_uv: int
    lossy: int
    ubwc_cfg: tuple[int, int, int, int, int, int, int, int, int, int, int, int]
    linear_y: Path
    linear_uv: Path | None
    tile_uncomp_y: Path
    tile_uncomp_uv: Path | None
    tile_comp_y: Path
    tile_comp_uv: Path | None
    meta_y: Path
    meta_uv: Path | None

    @property
    def has_uv(self) -> bool:
        return self.fmt in ("nv12", "p010")

    @property
    def tile_w(self) -> int:
        return 16 if self.fmt.startswith("rgba") else 32

    @property
    def tile_h(self) -> int:
        if self.fmt == "p010":
            return 4
        if self.fmt == "nv12":
            return 8
        return 4

    @property
    def bytes_per_pixel(self) -> int:
        return 2 if self.fmt == "p010" else (1 if self.fmt == "nv12" else 4)

    @property
    def tile_cols(self) -> int:
        return ceil_div(self.width, self.tile_w)

    @property
    def stored_tile_cols(self) -> int:
        stored_width = self.pitch_y // self.bytes_per_pixel
        return ceil_div(stored_width, self.tile_w)

    @property
    def y_tile_rows(self) -> int:
        return self.stored_y // self.tile_h

    @property
    def uv_tile_rows(self) -> int:
        return 0 if not self.has_uv else self.stored_uv // self.tile_h

    @property
    def active_y_tile_rows(self) -> int:
        return ceil_div(self.height, self.tile_h)

    @property
    def active_uv_height(self) -> int:
        return ceil_div(self.height, 2)

    @property
    def active_uv_tile_rows(self) -> int:
        return 0 if not self.has_uv else ceil_div(self.active_uv_height, self.tile_h)

    @property
    def meta_y_words64(self) -> int:
        return count_words64(self.meta_y)

    @property
    def meta_uv_words64(self) -> int:
        return count_words64(self.meta_uv) if self.meta_uv else 0

    @property
    def tile_comp_y_words64(self) -> int:
        return count_words64(self.tile_comp_y)

    @property
    def tile_comp_uv_words64(self) -> int:
        return count_words64(self.tile_comp_uv) if self.tile_comp_uv else 0

    @property
    def tile_uncomp_y_words64(self) -> int:
        return count_words64(self.tile_uncomp_y)

    @property
    def tile_uncomp_uv_words64(self) -> int:
        return count_words64(self.tile_uncomp_uv) if self.tile_uncomp_uv else 0

    @property
    def meta_y_lines_from_file(self) -> int:
        return (self.meta_y_words64 * 8 + self.meta_pitch_y - 1) // self.meta_pitch_y

    @property
    def meta_uv_lines_from_file(self) -> int:
        if not self.has_uv:
            return 0
        return (self.meta_uv_words64 * 8 + self.meta_pitch_uv - 1) // self.meta_pitch_uv


def case_readme(path: Path) -> Path:
    readme = path / "Readme.txt"
    if readme.exists():
        return readme
    readme = path / "ReadMe.txt"
    if readme.exists():
        return readme
    raise FileNotFoundError(f"Missing Readme.txt/ReadMe.txt under {path}")


def normalize_format(fmt_raw: str) -> str:
    text = fmt_raw.strip().lower()
    if text in ("p010", "g016"):
        return "p010"
    if text in ("nv12", "ubwc_nv_12"):
        return "nv12"
    if "1010102" in text:
        return "rgba1010102"
    if "r8g8b8a8" in text or "rgba8888" in text:
        return "rgba8888"
    return text


def load_case(path: Path) -> VectorCase:
    text = case_readme(path).read_text()
    fmt_raw = re.search(r"^Image format\s*:\s*(\S+)", text, re.M).group(1).lower()
    fmt = normalize_format(fmt_raw)
    case_id = {"rgba8888": 0, "rgba1010102": 1, "nv12": 2, "p010": 3}[fmt]
    size = re.search(r"^Actual Image size\(Pixels\)\s*:\s*([0-9]+)\s*x\s*([0-9]+)", text, re.M)
    width = int(size.group(1))
    height = int(size.group(2))
    stored_y = parse_int_field(text, "Aligned Height for Pixel Data P0")
    stored_uv = parse_int_field(text, "Aligned Height for Pixel Data P1") if fmt in ("nv12", "p010") else 0
    pitch_y = parse_int_field(text, "Pitch for Pixel Data P0")
    pitch_uv = parse_int_field(text, "Pitch for Pixel Data P1") if fmt in ("nv12", "p010") else 0
    meta_pitch_y = parse_int_field(text, "Pitch for Meta Data P0")
    meta_pitch_uv = parse_int_field(text, "Pitch for Meta Data P1") if fmt in ("nv12", "p010") else 0

    def p(label: str) -> Path | None:
        file_name = parse_file_field(text, label)
        return path / file_name if file_name else None

    linear_y = p("Linear Image") or p("Linear Image RGB/Y-plane") or p("Linear Image Y-plane")
    linear_uv = p("Linear Image UV-plane")
    tile_uncomp_y = p("Tiled Uncompressed Image RGB/Y-plane")
    tile_uncomp_uv = p("Tiled Uncompressed Image UV-plane")
    tile_comp_y = p("Tiled Compressed Image RGB/Y-plane")
    tile_comp_uv = p("Tiled Compressed Image UV-plane")
    meta_y = p("Metadata RGB/Y-plane")
    meta_uv = p("Metadata UV-plane")

    meta_base_y = parse_hex_field(text, "Base Address Meta RGB/Y-plane")
    meta_base_uv = parse_hex_field(text, "Base Address Meta UV-plane")
    tile_base_y = parse_hex_field(text, "Base Address Tile RGB/Y-plane")
    tile_base_uv = parse_hex_field(text, "Base Address Tile UV-plane")
    lossy = parse_optional_int_field(text, "LOSSY")
    ubwc_cfg = tuple(parse_optional_int_field(text, f"UBWC_CFG_{idx}") for idx in range(12))
    if (meta_base_y == 0 and meta_base_uv == 0 and
            tile_base_y == 0 and tile_base_uv == 0):
        meta_y_size = align_up(count_words64(meta_y) * 8, 4096)
        tile_y_size = align_up(pitch_y * stored_y, 4096)
        meta_base_y = 0
        tile_base_y = meta_base_y + meta_y_size
        if fmt in ("nv12", "p010"):
            meta_uv_size = align_up(count_words64(meta_uv) * 8, 4096)
            meta_base_uv = tile_base_y + tile_y_size
            tile_base_uv = meta_base_uv + meta_uv_size

    return VectorCase(
        name=re.sub(r"^enc_from_[a-z0-9_]+_pattern_", "", path.name),
        path=path,
        fmt=fmt,
        case_id=case_id,
        width=width,
        height=height,
        stored_y=stored_y,
        stored_uv=stored_uv,
        pitch_y=pitch_y,
        pitch_uv=pitch_uv,
        meta_pitch_y=meta_pitch_y,
        meta_pitch_uv=meta_pitch_uv,
        meta_base_y=meta_base_y,
        meta_base_uv=meta_base_uv,
        tile_base_y=tile_base_y,
        tile_base_uv=tile_base_uv,
        lossy=lossy,
        ubwc_cfg=ubwc_cfg,
        linear_y=linear_y,
        linear_uv=linear_uv,
        tile_uncomp_y=tile_uncomp_y,
        tile_uncomp_uv=tile_uncomp_uv,
        tile_comp_y=tile_comp_y,
        tile_comp_uv=tile_comp_uv,
        meta_y=meta_y,
        meta_uv=meta_uv,
    )


def make_param_flags(top: str, case: VectorCase, dec: bool) -> str:
    h_total = case.width + 304
    v_total = case.height + 60
    cfg_tile_cols = case.stored_tile_cols if dec else case.tile_cols
    cfg_y_stored_h = max(case.stored_y, case.height) if dec else case.stored_y
    cfg_uv_stored_h = max(case.stored_uv, case.active_uv_height) if (dec and case.has_uv) else case.stored_uv
    cfg_y_tile_rows = case.active_y_tile_rows if dec else case.y_tile_rows
    cfg_uv_tile_rows = case.active_uv_tile_rows if dec else case.uv_tile_rows
    params: dict[str, int] = {
        "CASE_ID": case.case_id,
        "IMG_W": case.width,
        "COM_BUF_AW": 12,
        "CASE_TILE_EXPECT_LINEAR": 0 if dec else 1,
        "CASE_CI_LOSSY": case.lossy,
        "CASE_UBWC_CFG_0": case.ubwc_cfg[0],
        "CASE_UBWC_CFG_1": case.ubwc_cfg[1],
        "CASE_UBWC_CFG_2": case.ubwc_cfg[2],
        "CASE_UBWC_CFG_3": case.ubwc_cfg[3],
        "CASE_UBWC_CFG_4": case.ubwc_cfg[4],
        "CASE_UBWC_CFG_5": case.ubwc_cfg[5],
        "CASE_UBWC_CFG_6": case.ubwc_cfg[6],
        "CASE_UBWC_CFG_7": case.ubwc_cfg[7],
        "CASE_UBWC_CFG_8": case.ubwc_cfg[8],
        "CASE_UBWC_CFG_9": case.ubwc_cfg[9],
        "CASE_UBWC_CFG_10": case.ubwc_cfg[10],
        "CASE_UBWC_CFG_11": case.ubwc_cfg[11],
    }

    if dec:
        params.update({
            "TB_REAL_VIVO_MODE": 0,
            "FORCE_FULL_PAYLOAD_CASE": 0,
            "CASE_OTF_H_TOTAL": h_total,
            "CASE_OTF_H_SYNC": 44,
            "CASE_OTF_H_BP": 148,
            "CFG_OTF_V_TOTAL": v_total,
            "CFG_OTF_V_SYNC": 5,
            "CFG_OTF_V_BP": 36,
        })

    if case.fmt.startswith("rgba"):
        params.update({
            "RGBA_ACTIVE_H": case.height,
            "RGBA_STORED_H": cfg_y_stored_h,
            "RGBA_TILE_PITCH": case.pitch_y,
            "RGBA_TILE_COLS": cfg_tile_cols,
            "RGBA_TILE_ROWS": cfg_y_tile_rows,
            "RGBA_META_WORDS64": case.meta_y_words64,
            "CFG_RGBA_TILE_BASE_Y_ADDR": case.tile_base_y,
            "CFG_RGBA_META_BASE_Y_ADDR": case.meta_base_y,
        })
        if dec:
            params.update({
                "RGBA_TILE_X_COUNT": cfg_tile_cols,
                "RGBA_TILE_Y_COUNT": cfg_y_tile_rows,
                "RGBA_META_PITCH": case.meta_pitch_y,
                "RGBA_META_LINES": case.meta_y_lines_from_file,
            })
    elif case.fmt == "nv12":
        params.update({
            "CFG_NV12_ACTIVE_H": case.height,
            "CFG_NV12_Y_STORED_H": cfg_y_stored_h,
            "CFG_NV12_UV_STORED_H": cfg_uv_stored_h,
            "CFG_NV12_TILE_PITCH": case.pitch_y,
            "CFG_NV12_Y_TILE_COLS": cfg_tile_cols,
            "CFG_NV12_UV_TILE_COLS": cfg_tile_cols,
            "CFG_NV12_Y_TILE_ROWS": cfg_y_tile_rows,
            "CFG_NV12_UV_TILE_ROWS": cfg_uv_tile_rows,
            "CFG_NV12_COMP_Y_WORDS64": case.tile_comp_y_words64,
            "CFG_NV12_COMP_UV_WORDS64": case.tile_comp_uv_words64,
            "CFG_NV12_META_Y_WORDS64": case.meta_y_words64,
            "CFG_NV12_META_UV_WORDS64": case.meta_uv_words64,
            "CFG_NV12_TILE_BASE_Y_ADDR": case.tile_base_y,
            "CFG_NV12_TILE_BASE_UV_ADDR": case.tile_base_uv,
            "CFG_NV12_DUMP_TILE_BASE_Y_ADDR": case.tile_base_y,
            "CFG_NV12_DUMP_TILE_BASE_UV_ADDR": case.tile_base_uv,
            "CFG_NV12_META_BASE_Y_ADDR": case.meta_base_y,
            "CFG_NV12_META_BASE_UV_ADDR": case.meta_base_uv,
        })
        if dec:
            params.update({
                "CFG_NV12_TILE_X_COUNT": cfg_tile_cols,
                "CFG_NV12_Y_TILE_Y_COUNT": cfg_y_tile_rows,
                "CFG_NV12_UV_TILE_Y_COUNT": cfg_uv_tile_rows,
                "CFG_NV12_UNCOMP_Y_WORDS64": case.tile_uncomp_y_words64,
                "CFG_NV12_UNCOMP_UV_WORDS64": case.tile_uncomp_uv_words64,
                "CFG_NV12_META_PITCH": case.meta_pitch_y,
                "CFG_NV12_META_Y_LINES": case.meta_y_lines_from_file,
                "CFG_NV12_META_UV_LINES": case.meta_uv_lines_from_file,
            })
    else:
        params.update({
            "CFG_G016_ACTIVE_H": case.height,
            "CFG_G016_Y_STORED_H": cfg_y_stored_h,
            "CFG_G016_UV_STORED_H": cfg_uv_stored_h,
            "CFG_G016_TILE_PITCH": case.pitch_y,
            "CFG_G016_Y_TILE_COLS": cfg_tile_cols,
            "CFG_G016_UV_TILE_COLS": cfg_tile_cols,
            "CFG_G016_Y_TILE_ROWS": cfg_y_tile_rows,
            "CFG_G016_UV_TILE_ROWS": cfg_uv_tile_rows,
            "CFG_G016_COMP_Y_WORDS64": case.tile_comp_y_words64,
            "CFG_G016_COMP_UV_WORDS64": case.tile_comp_uv_words64,
            "CFG_G016_META_Y_WORDS64": case.meta_y_words64,
            "CFG_G016_META_UV_WORDS64": case.meta_uv_words64,
            "CFG_G016_TILE_BASE_Y_ADDR": case.tile_base_y,
            "CFG_G016_TILE_BASE_UV_ADDR": case.tile_base_uv,
            "CFG_G016_META_BASE_Y_ADDR": case.meta_base_y,
            "CFG_G016_META_BASE_UV_ADDR": case.meta_base_uv,
        })
        if dec:
            params.update({
                "CFG_G016_TILE_X_COUNT": cfg_tile_cols,
                "CFG_G016_Y_TILE_Y_COUNT": cfg_y_tile_rows,
                "CFG_G016_UV_TILE_Y_COUNT": cfg_uv_tile_rows,
                "CFG_G016_UNCOMP_Y_WORDS64": case.tile_uncomp_y_words64,
                "CFG_G016_UNCOMP_UV_WORDS64": case.tile_uncomp_uv_words64,
                "CFG_G016_META_PITCH": case.meta_pitch_y,
                "CFG_G016_META_Y_LINES": case.meta_y_lines_from_file,
                "CFG_G016_META_UV_LINES": case.meta_uv_lines_from_file,
            })

    def fmt_param_value(key: str, value: int) -> str:
        if key.endswith("_ADDR"):
            return str(value & ((1 << 64) - 1))
        return str(value)

    return " ".join(f"-pvalue+{top}.{key}={fmt_param_value(key, value)}" for key, value in params.items())


def run_cmd(cmd: list[str], log_file: Path | None = None) -> int:
    print("+", " ".join(shlex.quote(x) for x in cmd), flush=True)
    if log_file:
        log_file.parent.mkdir(parents=True, exist_ok=True)
        with log_file.open("a") as fh:
            proc = subprocess.run(cmd, stdout=fh, stderr=subprocess.STDOUT)
            return proc.returncode
    return subprocess.run(cmd).returncode


def run_make(target: str, top: str, build_root: Path, flags: str, run_args: str, log: Path) -> int:
    make_cmd = (
        f"source {shlex.quote(str(ENV_SCRIPT))}; "
        f"make -C {shlex.quote(str(SIM_DIR))} "
        f"TOP={shlex.quote(top)} "
        f"BUILD_ROOT={shlex.quote(str(build_root))} "
        f'TB_PARAM_FLAGS="{flags}" '
        f'RUN_ARGS="{run_args}" '
        f"{target}"
    )
    return run_cmd(["tcsh", "-c", make_cmd], log)


def prepare_otf_stream(case: VectorCase,
                       build_dir: Path,
                       expected_y: Path | None = None,
                       expected_uv: Path | None = None) -> None:
    out = build_dir / "input_otf_stream.txt"
    expected_y = expected_y or case.linear_y
    expected_uv = expected_uv or case.linear_uv
    if case.fmt in ("rgba8888", "rgba1010102"):
        cmd = [
            sys.executable, str(OTF_CASE_TOOL), "gen-stream",
            "--format", case.fmt,
            "--expected", str(expected_y),
            "--width", str(case.width),
            "--stored-height", str(case.height),
            "--out", str(out),
        ]
    else:
        phase_arg = "--p010-uv-phase" if case.fmt == "p010" else "--nv12-uv-phase"
        cmd = [
            sys.executable, str(OTF_CASE_TOOL), "gen-stream",
            "--format", case.fmt,
            "--expected-y", str(expected_y),
            "--expected-uv", str(expected_uv),
            "--width", str(case.width),
            "--stored-y-height", str(case.height),
            "--stored-uv-height", str(case.active_uv_height),
            phase_arg, "even",
            "--out", str(out),
        ]
    subprocess.check_call(cmd)


def prepare_enc_files(case: VectorCase, build_dir: Path) -> None:
    build_dir.mkdir(parents=True, exist_ok=True)
    write_words64(build_dir / "expected_tile_plane0.memh", active_linear_words(case, 0))
    write_words64(build_dir / "expected_meta_plane0.memh",
                  normalize_enc_meta_words(case, 0, load_words64(case.meta_y)))
    strip_at_lines(case.tile_comp_y, build_dir / "expected_cmp_plane0.memh")
    if case.has_uv:
        write_words64(build_dir / "expected_tile_plane1.memh", active_linear_words(case, 1))
        write_words64(build_dir / "expected_meta_plane1.memh",
                      normalize_enc_meta_words(case, 1, load_words64(case.meta_uv)))
        strip_at_lines(case.tile_comp_uv, build_dir / "expected_cmp_plane1.memh")
    prepare_otf_stream(case, build_dir)


def prepare_dec_files(case: VectorCase, build_dir: Path) -> None:
    build_dir.mkdir(parents=True, exist_ok=True)
    strip_at_lines(case.meta_y, build_dir / "input_meta_plane0.txt")
    strip_at_lines(case.tile_comp_y, build_dir / "input_tile_plane0.txt")
    strip_at_lines(case.tile_uncomp_y, build_dir / "inject_tile_plane0.txt")
    if case.has_uv:
        strip_at_lines(case.meta_uv, build_dir / "input_meta_plane1.txt")
        strip_at_lines(case.tile_comp_uv, build_dir / "input_tile_plane1.txt")
        strip_at_lines(case.tile_uncomp_uv, build_dir / "inject_tile_plane1.txt")
    else:
        for name in ("input_meta_plane1.txt", "input_tile_plane1.txt", "inject_tile_plane1.txt"):
            (build_dir / name).write_text("")
    if case.lossy and case.fmt in ("rgba8888", "rgba1010102"):
        expected_linear_y = build_dir / "expected_linear_from_uncompressed_plane0.memh"
        write_words64(expected_linear_y, dec_tile_to_linear_words(case, 0))
        prepare_otf_stream(case, build_dir, expected_y=expected_linear_y)
    else:
        prepare_otf_stream(case, build_dir)
    shutil.copy2(build_dir / "input_otf_stream.txt", build_dir / "expected_otf_stream.txt")


def copy_waves(build_dir: Path, archive: Path, prefix: str) -> None:
    archive.mkdir(parents=True, exist_ok=True)
    for fsdb in build_dir.glob("*.fsdb"):
        shutil.copy2(fsdb, archive / f"{prefix}_{fsdb.name}")


def log_has_failure(log: Path) -> bool:
    if not log.exists():
        return True
    text = log.read_text(errors="ignore")
    return bool(re.search(r"(^|[ \t])FAIL:|\[TB\]\[ERROR\]|\$fatal|Fatal:", text, re.M))


def run_one(kind: str, case: VectorCase, root: Path, archive: Path) -> bool:
    top = ENC_TOP if kind == "enc" else DEC_TOP
    build_root = root / kind / case.name
    build_dir = build_root / f"{top}_fake"
    log = build_root / "run_full.log"
    flags = make_param_flags(top, case, dec=(kind == "dec"))
    run_args = "+tb_frame_repeat=1 +tb_timeout_cycles=80000000 +tb_idle_gap_cycles=12000000"

    if kind == "enc":
        prepare_enc_files(case, build_dir)
    else:
        prepare_dec_files(case, build_dir)

    rc = run_make("comp", top, build_root, flags, run_args, log)
    if rc == 0:
        rc = run_make("run", top, build_root, flags, run_args, log)
    copy_waves(build_dir, archive, f"{kind}_{case.name}")
    passed = rc == 0 and not log_has_failure(build_dir / "run.log") and not log_has_failure(log)
    print(f"[{'PASS' if passed else 'FAIL'}] {kind} {case.name}", flush=True)
    return passed


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--enc-only", action="store_true")
    ap.add_argument("--dec-only", action="store_true")
    ap.add_argument("--smoke", action="store_true", help="Run only the first vector directory.")
    ap.add_argument("--case", action="append", default=[], help="Run cases whose directory-derived name contains this text.")
    ap.add_argument("--source-tag", default="r7130", help="Vector source tag, e.g. r7130 or r7928.")
    ap.add_argument("--keep-root", type=Path)
    args = ap.parse_args()

    source_tag = args.source_tag.strip().lower()
    if not re.fullmatch(r"[a-z0-9_]+", source_tag):
        ap.error("--source-tag may only contain lowercase letters, digits, and underscore")
    cases = [load_case(p) for p in sorted(VECTOR_ROOT.glob(f"enc_from_{source_tag}_pattern_*"))]
    if args.smoke:
        cases = [case for case in cases if case.name.startswith("256x160_rgba8888")][:1]
    if args.case:
        cases = [case for case in cases if any(token in case.name for token in args.case)]
    kinds = ["enc", "dec"]
    if args.enc_only:
        kinds = ["enc"]
    if args.dec_only:
        kinds = ["dec"]

    ts = _dt.datetime.now().strftime(f"{source_tag}_%Y%m%d_%H%M%S")
    root = args.keep_root or (SIM_DIR / "build" / ts)
    archive = root / "waves"
    summary = root / "summary.txt"
    root.mkdir(parents=True, exist_ok=True)

    total = 0
    passed = 0
    failed: list[str] = []
    for case in cases:
        for kind in kinds:
            total += 1
            if run_one(kind, case, root, archive):
                passed += 1
            else:
                failed.append(f"{kind}:{case.name}")

    summary.write_text(
        f"total={total}\npass={passed}\nfail={len(failed)}\n"
        f"root={root}\nwaves={archive}\n"
        + "".join(f"FAIL {item}\n" for item in failed)
    )
    print(f"SUMMARY total={total} pass={passed} fail={len(failed)}")
    print(f"RUN_ROOT={root}")
    print(f"WAVE_ARCHIVE={archive}")
    print(f"SUMMARY_FILE={summary}")
    return 0 if not failed else 1


if __name__ == "__main__":
    raise SystemExit(main())
