
   `undef ubwc_x2x_AS_IS_OR_US_INLAST
   `undef ubwc_x2x_BUS_AWPYLD_W_SP
   `undef ubwc_x2x_BUS_BPYLD_W_SP
   `undef ubwc_x2x_BUS_WPYLD_W_MP
   `undef ubwc_x2x_BUS_WPYLD_W_SP
   `undef ubwc_x2x_DWC_NO_CDC_INIT
   `undef ubwc_x2x_DWC_NO_TST_MODE
   `undef ubwc_x2x_DW_HOLD_MUX_DELAY
   `undef ubwc_x2x_DW_SETUP_MUX_DELAY
   `undef ubwc_x2x_EXCLUS
   `undef ubwc_x2x_IDLE_CTRL
   `undef ubwc_x2x_LOCKED
   `undef ubwc_x2x_MUL_XACT_INLAST
   `undef ubwc_x2x_MUL_XACT_NOTLAST
   `undef ubwc_x2x_MUL_XACT_OR_US_INLAST
   `undef ubwc_x2x_MUL_XACT_OR_US_NOTLAST
   `undef ubwc_x2x_MUX_CROSS
   `undef ubwc_x2x_MUX_FI_LAST
   `undef ubwc_x2x_MUX_FI_MUL
   `undef ubwc_x2x_MUX_OVERONE
   `undef ubwc_x2x_MUX_WRAP
   `undef ubwc_x2x_MUX_WRAP_BOUND
   `undef ubwc_x2x_MXI_FI
   `undef ubwc_x2x_MXI_WRAP
   `undef ubwc_x2x_MXUI_CROSS
   `undef ubwc_x2x_MXUI_DS
   `undef ubwc_x2x_MXUI_FI_DS
   `undef ubwc_x2x_MXUI_FI_MUL
   `undef ubwc_x2x_MXUI_FI_SINGLE
   `undef ubwc_x2x_MXUI_NO_CROSS
   `undef ubwc_x2x_MXUI_SINGLE
   `undef ubwc_x2x_NORMAL
   `undef ubwc_x2x_NO_ACTION
   `undef ubwc_x2x_PARAM_VARS_PROC
   `undef ubwc_x2x_RM_BCM01
   `undef ubwc_x2x_RM_BCM02
   `undef ubwc_x2x_RM_BCM03
   `undef ubwc_x2x_RM_BCM05
   `undef ubwc_x2x_RM_BCM05_ATV
   `undef ubwc_x2x_RM_BCM06
   `undef ubwc_x2x_RM_BCM06_ATV
   `undef ubwc_x2x_RM_BCM07
   `undef ubwc_x2x_RM_BCM07_ATV
   `undef ubwc_x2x_RM_BCM07_EFES
   `undef ubwc_x2x_RM_BCM08
   `undef ubwc_x2x_RM_BCM09
   `undef ubwc_x2x_RM_BCM09_DP
   `undef ubwc_x2x_RM_BCM09_ECC
   `undef ubwc_x2x_RM_BCM10
   `undef ubwc_x2x_RM_BCM11
   `undef ubwc_x2x_RM_BCM12
   `undef ubwc_x2x_RM_BCM15
   `undef ubwc_x2x_RM_BCM16
   `undef ubwc_x2x_RM_BCM21
   `undef ubwc_x2x_RM_BCM21_A
   `undef ubwc_x2x_RM_BCM21_ATV
   `undef ubwc_x2x_RM_BCM21_CG
   `undef ubwc_x2x_RM_BCM22
   `undef ubwc_x2x_RM_BCM22_ATV
   `undef ubwc_x2x_RM_BCM23
   `undef ubwc_x2x_RM_BCM23_ATV
   `undef ubwc_x2x_RM_BCM24
   `undef ubwc_x2x_RM_BCM24_AP
   `undef ubwc_x2x_RM_BCM25
   `undef ubwc_x2x_RM_BCM25_ATV
   `undef ubwc_x2x_RM_BCM26
   `undef ubwc_x2x_RM_BCM27
   `undef ubwc_x2x_RM_BCM28
   `undef ubwc_x2x_RM_BCM29
   `undef ubwc_x2x_RM_BCM30
   `undef ubwc_x2x_RM_BCM31
   `undef ubwc_x2x_RM_BCM32
   `undef ubwc_x2x_RM_BCM35
   `undef ubwc_x2x_RM_BCM35_T
   `undef ubwc_x2x_RM_BCM36
   `undef ubwc_x2x_RM_BCM36_NHS
   `undef ubwc_x2x_RM_BCM37
   `undef ubwc_x2x_RM_BCM38
   `undef ubwc_x2x_RM_BCM38_ADP
   `undef ubwc_x2x_RM_BCM38_AP
   `undef ubwc_x2x_RM_BCM38_ECC
   `undef ubwc_x2x_RM_BCM39
   `undef ubwc_x2x_RM_BCM40
   `undef ubwc_x2x_RM_BCM41
   `undef ubwc_x2x_RM_BCM42
   `undef ubwc_x2x_RM_BCM43
   `undef ubwc_x2x_RM_BCM43_NRO
   `undef ubwc_x2x_RM_BCM44
   `undef ubwc_x2x_RM_BCM44_NRO
   `undef ubwc_x2x_RM_BCM46_A
   `undef ubwc_x2x_RM_BCM46_AA
   `undef ubwc_x2x_RM_BCM46_B
   `undef ubwc_x2x_RM_BCM46_C
   `undef ubwc_x2x_RM_BCM46_D
   `undef ubwc_x2x_RM_BCM46_E
   `undef ubwc_x2x_RM_BCM46_F
   `undef ubwc_x2x_RM_BCM47
   `undef ubwc_x2x_RM_BCM48
   `undef ubwc_x2x_RM_BCM48_DM
   `undef ubwc_x2x_RM_BCM48_SV
   `undef ubwc_x2x_RM_BCM49
   `undef ubwc_x2x_RM_BCM49_SV
   `undef ubwc_x2x_RM_BCM50
   `undef ubwc_x2x_RM_BCM51
   `undef ubwc_x2x_RM_BCM52
   `undef ubwc_x2x_RM_BCM53
   `undef ubwc_x2x_RM_BCM54
   `undef ubwc_x2x_RM_BCM55
   `undef ubwc_x2x_RM_BCM55_C
   `undef ubwc_x2x_RM_BCM56
   `undef ubwc_x2x_RM_BCM57
   `undef ubwc_x2x_RM_BCM58
   `undef ubwc_x2x_RM_BCM59
   `undef ubwc_x2x_RM_BCM60
   `undef ubwc_x2x_RM_BCM62
   `undef ubwc_x2x_RM_BCM63
   `undef ubwc_x2x_RM_BCM64
   `undef ubwc_x2x_RM_BCM64_TD
   `undef ubwc_x2x_RM_BCM65
   `undef ubwc_x2x_RM_BCM65_ATV
   `undef ubwc_x2x_RM_BCM65_TD
   `undef ubwc_x2x_RM_BCM66
   `undef ubwc_x2x_RM_BCM66_EFES
   `undef ubwc_x2x_RM_BCM71
   `undef ubwc_x2x_RM_BCM72
   `undef ubwc_x2x_RM_BCM73
   `undef ubwc_x2x_RM_BCM74
   `undef ubwc_x2x_RM_BCM76
   `undef ubwc_x2x_RM_BCM77
   `undef ubwc_x2x_RM_BCM78
   `undef ubwc_x2x_RM_BCM79
   `undef ubwc_x2x_RM_BCM85
   `undef ubwc_x2x_RM_BCM86
   `undef ubwc_x2x_RM_BCM87
   `undef ubwc_x2x_RM_BCM90
   `undef ubwc_x2x_RM_BCM95
   `undef ubwc_x2x_RM_BCM95_E
   `undef ubwc_x2x_RM_BCM95_I
   `undef ubwc_x2x_RM_BCM95_IE
   `undef ubwc_x2x_RM_BCM98
   `undef ubwc_x2x_RM_BCM99
   `undef ubwc_x2x_RM_BCM99_N
   `undef ubwc_x2x_RM_BVM01
   `undef ubwc_x2x_RM_BVM02
   `undef ubwc_x2x_RM_SVA01
   `undef ubwc_x2x_RM_SVA02
   `undef ubwc_x2x_RM_SVA03
   `undef ubwc_x2x_RM_SVA04
   `undef ubwc_x2x_RM_SVA05
   `undef ubwc_x2x_RM_SVA06
   `undef ubwc_x2x_RM_SVA07
   `undef ubwc_x2x_RM_SVA99
   `undef ubwc_x2x_SIM_M_CLK_PERIOD
   `undef ubwc_x2x_SIM_S_CLK_PERIOD
   `undef ubwc_x2x_SINGLE_XACT_INLAST
   `undef ubwc_x2x_USE_FOUNDATION
   `undef ubwc_x2x_USE_PARAM_VARS_PROC
   `undef ubwc_x2x_X2X_0LOG2_MAX_MP_BYTES
   `undef ubwc_x2x_X2X_0LOG2_MAX_SP_BYTES
   `undef ubwc_x2x_X2X_ADDR_CH
   `undef ubwc_x2x_X2X_ADDR_TRK_W
   `undef ubwc_x2x_X2X_ARPYLD_ADDR_LHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_ADDR_LHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_ADDR_MP
   `undef ubwc_x2x_X2X_ARPYLD_ADDR_RHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_ADDR_RHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_ADDR_SP
   `undef ubwc_x2x_X2X_ARPYLD_BURST_LHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_BURST_LHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_BURST_MP
   `undef ubwc_x2x_X2X_ARPYLD_BURST_RHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_BURST_RHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_BURST_SP
   `undef ubwc_x2x_X2X_ARPYLD_CACHE_LHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_CACHE_LHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_CACHE_MP
   `undef ubwc_x2x_X2X_ARPYLD_CACHE_RHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_CACHE_RHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_CACHE_SP
   `undef ubwc_x2x_X2X_ARPYLD_ID_LHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_ID_LHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_ID_MP
   `undef ubwc_x2x_X2X_ARPYLD_ID_RHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_ID_RHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_ID_SP
   `undef ubwc_x2x_X2X_ARPYLD_LEN_LHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_LEN_LHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_LEN_MP
   `undef ubwc_x2x_X2X_ARPYLD_LEN_RHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_LEN_RHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_LEN_SP
   `undef ubwc_x2x_X2X_ARPYLD_LOCK_LHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_LOCK_LHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_LOCK_MP
   `undef ubwc_x2x_X2X_ARPYLD_LOCK_RHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_LOCK_RHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_LOCK_SP
   `undef ubwc_x2x_X2X_ARPYLD_PROT_LHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_PROT_LHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_PROT_MP
   `undef ubwc_x2x_X2X_ARPYLD_PROT_RHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_PROT_RHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_PROT_SP
   `undef ubwc_x2x_X2X_ARPYLD_SIZE_LHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_SIZE_LHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_SIZE_MP
   `undef ubwc_x2x_X2X_ARPYLD_SIZE_RHS_MP
   `undef ubwc_x2x_X2X_ARPYLD_SIZE_RHS_SP
   `undef ubwc_x2x_X2X_ARPYLD_SIZE_SP
   `undef ubwc_x2x_X2X_ARPYLD_W_MP
   `undef ubwc_x2x_X2X_ARPYLD_W_SP
   `undef ubwc_x2x_X2X_AR_BUF_DEPTH
   `undef ubwc_x2x_X2X_AR_BUF_DEPTH_L2
   `undef ubwc_x2x_X2X_AR_BUF_DEPTH_P1L2
   `undef ubwc_x2x_X2X_AR_SBW
   `undef ubwc_x2x_X2X_AWPYLD_ADDR_LHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_ADDR_LHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_ADDR_MP
   `undef ubwc_x2x_X2X_AWPYLD_ADDR_RHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_ADDR_RHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_ADDR_SP
   `undef ubwc_x2x_X2X_AWPYLD_BURST_LHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_BURST_LHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_BURST_MP
   `undef ubwc_x2x_X2X_AWPYLD_BURST_RHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_BURST_RHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_BURST_SP
   `undef ubwc_x2x_X2X_AWPYLD_CACHE_LHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_CACHE_LHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_CACHE_MP
   `undef ubwc_x2x_X2X_AWPYLD_CACHE_RHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_CACHE_RHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_CACHE_SP
   `undef ubwc_x2x_X2X_AWPYLD_ID_LHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_ID_LHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_ID_MP
   `undef ubwc_x2x_X2X_AWPYLD_ID_RHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_ID_RHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_ID_SP
   `undef ubwc_x2x_X2X_AWPYLD_LEN_LHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_LEN_LHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_LEN_MP
   `undef ubwc_x2x_X2X_AWPYLD_LEN_RHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_LEN_RHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_LEN_SP
   `undef ubwc_x2x_X2X_AWPYLD_LOCK_LHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_LOCK_LHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_LOCK_MP
   `undef ubwc_x2x_X2X_AWPYLD_LOCK_RHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_LOCK_RHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_LOCK_SP
   `undef ubwc_x2x_X2X_AWPYLD_PROT_LHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_PROT_LHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_PROT_MP
   `undef ubwc_x2x_X2X_AWPYLD_PROT_RHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_PROT_RHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_PROT_SP
   `undef ubwc_x2x_X2X_AWPYLD_SIZE_LHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_SIZE_LHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_SIZE_MP
   `undef ubwc_x2x_X2X_AWPYLD_SIZE_RHS_MP
   `undef ubwc_x2x_X2X_AWPYLD_SIZE_RHS_SP
   `undef ubwc_x2x_X2X_AWPYLD_SIZE_SP
   `undef ubwc_x2x_X2X_AWPYLD_W_MP
   `undef ubwc_x2x_X2X_AWPYLD_W_SP
   `undef ubwc_x2x_X2X_AW_BUF_DEPTH
   `undef ubwc_x2x_X2X_AW_BUF_DEPTH_L2
   `undef ubwc_x2x_X2X_AW_BUF_DEPTH_P1L2
   `undef ubwc_x2x_X2X_AW_CH
   `undef ubwc_x2x_X2X_AW_CH_FIFO_W
   `undef ubwc_x2x_X2X_AW_MP_LRGR_OR_SAME
   `undef ubwc_x2x_X2X_AW_SBW
   `undef ubwc_x2x_X2X_AXI_MP_NUM_MASTERS
   `undef ubwc_x2x_X2X_AXI_MP_NUM_SLAVES
   `undef ubwc_x2x_X2X_AXI_SP_NUM_MASTERS
   `undef ubwc_x2x_X2X_AXI_SP_NUM_SLAVES
   `undef ubwc_x2x_X2X_BPYLD_ID_LHS_MP
   `undef ubwc_x2x_X2X_BPYLD_ID_LHS_SP
   `undef ubwc_x2x_X2X_BPYLD_ID_MP
   `undef ubwc_x2x_X2X_BPYLD_ID_RHS_MP
   `undef ubwc_x2x_X2X_BPYLD_ID_RHS_SP
   `undef ubwc_x2x_X2X_BPYLD_ID_SP
   `undef ubwc_x2x_X2X_BPYLD_RESP_LHS_MP
   `undef ubwc_x2x_X2X_BPYLD_RESP_LHS_SP
   `undef ubwc_x2x_X2X_BPYLD_RESP_MP
   `undef ubwc_x2x_X2X_BPYLD_RESP_RHS_MP
   `undef ubwc_x2x_X2X_BPYLD_RESP_RHS_SP
   `undef ubwc_x2x_X2X_BPYLD_RESP_SP
   `undef ubwc_x2x_X2X_BPYLD_W_MP
   `undef ubwc_x2x_X2X_BPYLD_W_SP
   `undef ubwc_x2x_X2X_BRW
   `undef ubwc_x2x_X2X_BSW
   `undef ubwc_x2x_X2X_BTW
   `undef ubwc_x2x_X2X_BT_FIXED
   `undef ubwc_x2x_X2X_BT_INCR
   `undef ubwc_x2x_X2X_BT_WRAP
   `undef ubwc_x2x_X2X_BT_X
   `undef ubwc_x2x_X2X_B_BUF_DEPTH
   `undef ubwc_x2x_X2X_B_BUF_DEPTH_L2
   `undef ubwc_x2x_X2X_B_BUF_DEPTH_P1L2
   `undef ubwc_x2x_X2X_B_SBW
   `undef ubwc_x2x_X2X_CH_SEL
   `undef ubwc_x2x_X2X_CH_SEL_0
   `undef ubwc_x2x_X2X_CLK_MODE
   `undef ubwc_x2x_X2X_CTW
   `undef ubwc_x2x_X2X_DATA_SEL_W
   `undef ubwc_x2x_X2X_DEFAULT_VAL
   `undef ubwc_x2x_X2X_HAS_ARSB
   `undef ubwc_x2x_X2X_HAS_AWSB
   `undef ubwc_x2x_X2X_HAS_BSB
   `undef ubwc_x2x_X2X_HAS_ET
   `undef ubwc_x2x_X2X_HAS_INC_DEBUG_LOGIC
   `undef ubwc_x2x_X2X_HAS_LOCKING
   `undef ubwc_x2x_X2X_HAS_MP_LRGR_ALTER
   `undef ubwc_x2x_X2X_HAS_PIPELINE
   `undef ubwc_x2x_X2X_HAS_RSB
   `undef ubwc_x2x_X2X_HAS_TX_UPSIZE
   `undef ubwc_x2x_X2X_HAS_TZ_SUPPORT
   `undef ubwc_x2x_X2X_HAS_WI_FAN_OUT
   `undef ubwc_x2x_X2X_HAS_WRAP_BURST
   `undef ubwc_x2x_X2X_HAS_WSB
   `undef ubwc_x2x_X2X_IDLE_VAL
   `undef ubwc_x2x_X2X_IDW_MP_LRGR_OR_SAME
   `undef ubwc_x2x_X2X_INTERNAL_AW
   `undef ubwc_x2x_X2X_INTERNAL_BW
   `undef ubwc_x2x_X2X_LEN_ONLY_ALTER
   `undef ubwc_x2x_X2X_LOG2_MAX_MP_BYTES
   `undef ubwc_x2x_X2X_LOG2_MAX_RCA_ID
   `undef ubwc_x2x_X2X_LOG2_MAX_SP_BYTES
   `undef ubwc_x2x_X2X_LOG2_MAX_SW
   `undef ubwc_x2x_X2X_LOG2_MAX_URIDA
   `undef ubwc_x2x_X2X_LOG2_MAX_WCA_ID
   `undef ubwc_x2x_X2X_LOG2_MP_BYTE
   `undef ubwc_x2x_X2X_LOG2_MP_SW
   `undef ubwc_x2x_X2X_LOG2_NUM_W_PORTS
   `undef ubwc_x2x_X2X_LOG2_SP_BYTE
   `undef ubwc_x2x_X2X_LOG2_SP_SW
   `undef ubwc_x2x_X2X_LOG2_WID
   `undef ubwc_x2x_X2X_LOG2_WIP_FIFO_D
   `undef ubwc_x2x_X2X_LOWPWR_HS_IF
   `undef ubwc_x2x_X2X_LOWPWR_NOPX_CNT
   `undef ubwc_x2x_X2X_LOWPWR_NOPX_CNT_LOG2
   `undef ubwc_x2x_X2X_LOWPWR_NOPX_CNT_P1_LOG2
   `undef ubwc_x2x_X2X_LTW
   `undef ubwc_x2x_X2X_LT_EX
   `undef ubwc_x2x_X2X_LT_LOCK
   `undef ubwc_x2x_X2X_LT_NORM
   `undef ubwc_x2x_X2X_MAX_DW
   `undef ubwc_x2x_X2X_MAX_MP_ALEN
   `undef ubwc_x2x_X2X_MAX_MP_ASIZE
   `undef ubwc_x2x_X2X_MAX_MP_BYTES
   `undef ubwc_x2x_X2X_MAX_MP_TOTAL_BYTE
   `undef ubwc_x2x_X2X_MAX_RCA_ID
   `undef ubwc_x2x_X2X_MAX_RCA_ID_P1L2
   `undef ubwc_x2x_X2X_MAX_SBW
   `undef ubwc_x2x_X2X_MAX_SP_ALEN
   `undef ubwc_x2x_X2X_MAX_SP_ASIZE
   `undef ubwc_x2x_X2X_MAX_SP_BYTES
   `undef ubwc_x2x_X2X_MAX_SP_TOTAL_BYTE
   `undef ubwc_x2x_X2X_MAX_SW
   `undef ubwc_x2x_X2X_MAX_URIDA
   `undef ubwc_x2x_X2X_MAX_UWIDA
   `undef ubwc_x2x_X2X_MAX_WCA_ID
   `undef ubwc_x2x_X2X_MAX_WCA_ID_P1L2
   `undef ubwc_x2x_X2X_MPDW256
   `undef ubwc_x2x_X2X_MPDW_GRTR_OR_EQ_128
   `undef ubwc_x2x_X2X_MPDW_GRTR_OR_EQ_16
   `undef ubwc_x2x_X2X_MPDW_GRTR_OR_EQ_256
   `undef ubwc_x2x_X2X_MPDW_GRTR_OR_EQ_32
   `undef ubwc_x2x_X2X_MPDW_GRTR_OR_EQ_64
   `undef ubwc_x2x_X2X_MP_AW
   `undef ubwc_x2x_X2X_MP_BLW
   `undef ubwc_x2x_X2X_MP_BLW_LRGR_OR_SAME
   `undef ubwc_x2x_X2X_MP_DW
   `undef ubwc_x2x_X2X_MP_DW_LARGER
   `undef ubwc_x2x_X2X_MP_IDW
   `undef ubwc_x2x_X2X_MP_LRGR_ALTER
   `undef ubwc_x2x_X2X_MP_SW
   `undef ubwc_x2x_X2X_MP_SYNC_DEPTH
   `undef ubwc_x2x_X2X_NOREQ_LOCKING
   `undef ubwc_x2x_X2X_NOT_ADDR_CH
   `undef ubwc_x2x_X2X_NOT_AW_CH
   `undef ubwc_x2x_X2X_NOT_R_CH
   `undef ubwc_x2x_X2X_NOT_W_CH
   `undef ubwc_x2x_X2X_NUM_W_PORTS
   `undef ubwc_x2x_X2X_N_TESTCASE_DUPLICATION
   `undef ubwc_x2x_X2X_PARAM_LOCKDOWN
   `undef ubwc_x2x_X2X_PTW
   `undef ubwc_x2x_X2X_PT_DATA
   `undef ubwc_x2x_X2X_PT_INSTRUCT
   `undef ubwc_x2x_X2X_PT_INSTRUCT_BIT
   `undef ubwc_x2x_X2X_PT_NORM
   `undef ubwc_x2x_X2X_PT_NSECURE
   `undef ubwc_x2x_X2X_PT_PRVLGD
   `undef ubwc_x2x_X2X_PT_PRVLGD_BIT
   `undef ubwc_x2x_X2X_PT_SECURE
   `undef ubwc_x2x_X2X_PT_SECURE_BIT
   `undef ubwc_x2x_X2X_RD_CHANNELS
   `undef ubwc_x2x_X2X_REQ_LOCKING
   `undef ubwc_x2x_X2X_RESP_DECERR
   `undef ubwc_x2x_X2X_RESP_EXOKAY
   `undef ubwc_x2x_X2X_RESP_OKAY
   `undef ubwc_x2x_X2X_RESP_SLVERR
   `undef ubwc_x2x_X2X_RPYLD_DATA_LHS_MP
   `undef ubwc_x2x_X2X_RPYLD_DATA_LHS_SP
   `undef ubwc_x2x_X2X_RPYLD_DATA_MP
   `undef ubwc_x2x_X2X_RPYLD_DATA_RHS_MP
   `undef ubwc_x2x_X2X_RPYLD_DATA_RHS_SP
   `undef ubwc_x2x_X2X_RPYLD_DATA_SP
   `undef ubwc_x2x_X2X_RPYLD_ID_LHS_MP
   `undef ubwc_x2x_X2X_RPYLD_ID_LHS_SP
   `undef ubwc_x2x_X2X_RPYLD_ID_MP
   `undef ubwc_x2x_X2X_RPYLD_ID_RHS_MP
   `undef ubwc_x2x_X2X_RPYLD_ID_RHS_SP
   `undef ubwc_x2x_X2X_RPYLD_ID_SP
   `undef ubwc_x2x_X2X_RPYLD_LAST_LHS_MP
   `undef ubwc_x2x_X2X_RPYLD_LAST_LHS_SP
   `undef ubwc_x2x_X2X_RPYLD_LAST_MP
   `undef ubwc_x2x_X2X_RPYLD_LAST_SP
   `undef ubwc_x2x_X2X_RPYLD_RESP_LHS_MP
   `undef ubwc_x2x_X2X_RPYLD_RESP_LHS_SP
   `undef ubwc_x2x_X2X_RPYLD_RESP_MP
   `undef ubwc_x2x_X2X_RPYLD_RESP_RHS_MP
   `undef ubwc_x2x_X2X_RPYLD_RESP_RHS_SP
   `undef ubwc_x2x_X2X_RPYLD_RESP_SP
   `undef ubwc_x2x_X2X_RPYLD_W_MP
   `undef ubwc_x2x_X2X_RPYLD_W_SP
   `undef ubwc_x2x_X2X_RRW
   `undef ubwc_x2x_X2X_RS_RATIO
   `undef ubwc_x2x_X2X_R_BUF_DEPTH
   `undef ubwc_x2x_X2X_R_BUF_DEPTH_L2
   `undef ubwc_x2x_X2X_R_BUF_DEPTH_P1L2
   `undef ubwc_x2x_X2X_R_CH
   `undef ubwc_x2x_X2X_R_LP_REG_DEPTH_L2
   `undef ubwc_x2x_X2X_R_LP_REG_DEPTH_PDL2
   `undef ubwc_x2x_X2X_R_SBW
   `undef ubwc_x2x_X2X_SEED
   `undef ubwc_x2x_X2X_SINGLE_CLK
   `undef ubwc_x2x_X2X_SPDW64
   `undef ubwc_x2x_X2X_SP_AW
   `undef ubwc_x2x_X2X_SP_BLW
   `undef ubwc_x2x_X2X_SP_DW
   `undef ubwc_x2x_X2X_SP_IDW
   `undef ubwc_x2x_X2X_SP_LRGR_ALTER
   `undef ubwc_x2x_X2X_SP_LRGR_US_ALTER
   `undef ubwc_x2x_X2X_SP_SW
   `undef ubwc_x2x_X2X_SP_SYNC_DEPTH
   `undef ubwc_x2x_X2X_SP_W_BEATS_PER_POP_W
   `undef ubwc_x2x_X2X_SP_W_RSFIFO_D
   `undef ubwc_x2x_X2X_SP_W_RSFIFO_D_L2
   `undef ubwc_x2x_X2X_SP_W_RSFIFO_D_P1L2
   `undef ubwc_x2x_X2X_SP_W_RSFIFO_W
   `undef ubwc_x2x_X2X_TB_DEBUG_LEVEL
   `undef ubwc_x2x_X2X_TX_ALTER
   `undef ubwc_x2x_X2X_TX_NO_ALTER
   `undef ubwc_x2x_X2X_UPSIZE_ANY_ASIZE
   `undef ubwc_x2x_X2X_USE_RANDOM_SEED
   `undef ubwc_x2x_X2X_VERIF_EN
   `undef ubwc_x2x_X2X_WID
   `undef ubwc_x2x_X2X_WIP_BYPASS
   `undef ubwc_x2x_X2X_WIP_FIFO_D
   `undef ubwc_x2x_X2X_WPYLD_DATA_LHS_MP
   `undef ubwc_x2x_X2X_WPYLD_DATA_LHS_SP
   `undef ubwc_x2x_X2X_WPYLD_DATA_MP
   `undef ubwc_x2x_X2X_WPYLD_DATA_RHS_MP
   `undef ubwc_x2x_X2X_WPYLD_DATA_RHS_SP
   `undef ubwc_x2x_X2X_WPYLD_DATA_SP
   `undef ubwc_x2x_X2X_WPYLD_ID_LHS_MP
   `undef ubwc_x2x_X2X_WPYLD_ID_LHS_SP
   `undef ubwc_x2x_X2X_WPYLD_ID_MP
   `undef ubwc_x2x_X2X_WPYLD_ID_RHS_MP
   `undef ubwc_x2x_X2X_WPYLD_ID_RHS_SP
   `undef ubwc_x2x_X2X_WPYLD_ID_SP
   `undef ubwc_x2x_X2X_WPYLD_LAST_LHS_MP
   `undef ubwc_x2x_X2X_WPYLD_LAST_LHS_SP
   `undef ubwc_x2x_X2X_WPYLD_LAST_MP
   `undef ubwc_x2x_X2X_WPYLD_LAST_SP
   `undef ubwc_x2x_X2X_WPYLD_STRB_LHS_MP
   `undef ubwc_x2x_X2X_WPYLD_STRB_LHS_SP
   `undef ubwc_x2x_X2X_WPYLD_STRB_MP
   `undef ubwc_x2x_X2X_WPYLD_STRB_RHS_MP
   `undef ubwc_x2x_X2X_WPYLD_STRB_RHS_SP
   `undef ubwc_x2x_X2X_WPYLD_STRB_SP
   `undef ubwc_x2x_X2X_WPYLD_W_MP
   `undef ubwc_x2x_X2X_WPYLD_W_SP
   `undef ubwc_x2x_X2X_WRAP_BURST
   `undef ubwc_x2x_X2X_W_BUF_DEPTH
   `undef ubwc_x2x_X2X_W_BUF_DEPTH_L2
   `undef ubwc_x2x_X2X_W_BUF_DEPTH_P1L2
   `undef ubwc_x2x_X2X_W_CH
   `undef ubwc_x2x_X2X_W_LP_REG_DEPTH_L2
   `undef ubwc_x2x_X2X_W_LP_REG_DEPTH_PDL2
   `undef ubwc_x2x_X2X_W_SBW
   `undef ubwc_x2x___GUARD__DW_AXI_X2X_ALL_INCLUDES__VH__
   `undef ubwc_x2x___GUARD__DW_AXI_X2X_BCM_PARAMS__VH__
   `undef ubwc_x2x___GUARD__DW_AXI_X2X_CC_CONSTANTS__VH__
   `undef ubwc_x2x___GUARD__DW_AXI_X2X_CONSTANTS__VH__
`define ubwc_x2x_cb_dummy_parameter_definition 1
`undef  ubwc_x2x_cb_dummy_parameter_definition
